Support for `pointer_to_address` instruction [ISSUE# 81]
uasys/swift pull request #137
Opened 2018-07-30 10:49 UTC by taufique71

Changes to handle `pointer_to_address` instruction

Resolves [Issue 81](https://github.com/themaplelab/swift/issues/81).

2018-07-30 16:17 UTC, karimhamdanali requested changes

2018-07-30 16:17 UTC, karimhamdanali commented on lib/WALASupport/SILWalaInstructionVisitor.cpp
> +
remove this empty line

2018-07-30 18:45 UTC, mmroz commented
So, I looked at the two instructions address_to_pointer and pointer_to_address and these 2 instructions are conversion instructions even though the types are internal. In the PR https://github.com/themaplelab/swift/pull/138 I made that change address_to_pointer and I think we should do that here too! Just add:

  jobject ConvertedTypeNode = Wala->makeConstant(CovertedType.c_str());
  jobject RawPointerCastNode = Wala->makeNode(CAstWrapper::CAST, ConvertedNode, ConvertedTypeNode);

2018-07-30 18:55 UTC, karimhamdanali commented
In addition to @mmroz comments, please resolve the merge conflicts before I approving this PR.

2018-07-31 10:43 UTC, taufique71 commented
@karimhamdanali, everything resolved. Please take a look if it's okay now.

2018-07-31 13:02 UTC, karimhamdanali commented
Thanks @taufique71. @mmroz, do these changes address your concerns as well?

2018-07-31 16:41 UTC, mmroz commented
Looks good!

2018-07-31 16:42 UTC, karimhamdanali approved these changes

2018-07-31 16:42 UTC, merged