Added support for the objc_method instruction
uasys/swift pull request #196
Opened 2018-08-21 12:37 UTC by mmroz

2018-08-22 21:04 UTC, karimhamdanali requested changes

2018-08-22 21:04 UTC, karimhamdanali commented on lib/WALASupport/SILWalaInstructionVisitor.cpp
> +  jobject Node = Wala->makeNode(CAstWrapper::OBJECT_REF, InterfaceNode, FuncNode );
Please fix spacing in args list.

2018-08-25 13:14 UTC, mmroz commented
Resolved!

2018-08-25 17:49 UTC, karimhamdanali approved these changes

2018-08-25 17:49 UTC, merged