Support for `end_lifetime` instruction
uasys/swift pull request #213
Opened 2018-08-28 11:37 UTC by taufique71

Resolves [Issue 156](https://github.com/themaplelab/swift/issues/156).

2018-08-28 16:41 UTC, karimhamdanali requested changes

2018-08-28 16:41 UTC, karimhamdanali commented on lib/WALASupport/SILWalaInstructionVisitor.cpp
> +  }
Please add an empty line here for better readability.

2018-08-30 04:22 UTC, bryantam approved these changes

2018-08-30 06:20 UTC, taufique71 commented on lib/WALASupport/SILWalaInstructionVisitor.cpp
> +  }
Done

2018-08-31 17:50 UTC, karimhamdanali approved these changes
LGTM

2018-08-31 17:50 UTC, merged