Support for `index_addr` instruction
uasys/swift pull request #96
Opened 2018-07-11 11:10 UTC by taufique71

Added WALA support for `index_addr` instruction

Resolves [Issue 77](https://github.com/themaplelab/swift/issues/77).

2018-07-11 11:10 UTC, taufique71 commented
@mmroz Can you please review the changes and point me out to things I am doing wrong or missing?

2018-07-13 19:02 UTC, karimhamdanali requested changes

2018-07-13 19:02 UTC, karimhamdanali commented on include/swift/WALASupport/SILWalaInstructionVisitor.h
> +void visitSILModule(SILModule *M);
please clean up the spacing here

2018-07-16 09:12 UTC, taufique71 commented
@karimhamdanali spacing is cleaned up.

2018-07-16 09:39 UTC, karimhamdanali commented
@mmroz I see that @taufique71  has requested your review on this one. Do you approve?

2018-07-16 11:02 UTC, mmroz commented
I don’t think this is correct because the instruction is about indexing into an array however the Node created is an ARRAY_REF which would be a mutable array. This instruction does not create an array or even use one

2018-07-16 12:20 UTC, taufique71 commented
@mmroz In your opinion, from available node types which node type resembles best what this instruction is doing?

2018-07-16 12:26 UTC, mmroz commented
Well with the given description of: “Given an address that references into an array of values, returns the address of the %1-th element relative to %0” and knowing %1 is an integer literal and %0 is the size of each element and the start of the array it may be possible to find the element and assign it to the node map

2018-07-16 18:59 UTC, taufique71 commented
@mmroz can you explain this part a little more?

> %0 is the size of each element and the start of the array

If I know the size of each element and I know the address of the first element then I can get address of n_th element. In that case what would the CAst node type be? ARRAY_LITERAL? But I am confused about size. Do we really know the size of the each element?

Plus I am confused about what ARRAY_REF actually means as there is no description there. Is it possible to clear me up if you know it?

2018-07-17 03:16 UTC, mmroz commented
can you review this and see what you think?


jobject SILWalaInstructionVisitor::visitIndexAddrInst(IndexAddrInst *IAI) {

  SILValue BaseValue = IAI->getBase();
  SILValue IndexValue = IAI->getIndex();

  jobject IndexNode = findAndRemoveCAstNode(IndexValue.getOpaqueValue());
  jobject BaseNode = findAndRemoveCAstNode(base.getOpaqueValue());

  if (Print) {
    llvm::outs() << "\t\t [BASE ADDR]:" << BaseValue.getOpaqueValue() << "\n";
    llvm::outs() << "\t\t [INDEX ADDR]:" << IndexValue.getOpaqueValue() << "\n";=
  }

  jobject IndexVarName = Wala->makeConstant("array_index");
  jobject IndexVar = Wala->makeNode(CAstWrapper::VAR, IndexVarName);
  jobject IndexNode = Wala->makeNode(CAstWrapper::ASSIGN, IndexVar, indexNode);

  auto IndexAddrNode = Wala->makeNode(CAstWrapper::BLOCK_EXPR, IndexNode, BaseNode);

  NodeMap.insert(std::make_pair(static_cast<ValueBase *>(IAI), IndexAddrNode));

  return IndexAddrNode;
}

2018-07-17 11:19 UTC, taufique71 commented
I have a couple of questions on above implementation -

1. Why do we need to create a new `IndexNode` with all those constant node creation, variable node creation and assignment node creation when we know that we can find this IndexNode created somewhere before?

2. `BLOCK_EXPR` resembles a sequential chain of simple expressions right? What I didn't get is how a BLOCK_EXPR resembles specifically array indexing here?

2018-07-17 11:33 UTC, mmroz commented
1. The Node we have is an IntegerLiteral but I want to represent an iterator for that value so I created a variable to represent that iterator. Its based off of how this handled memory accessing: https://www.programcreek.com/java-api-examples/index.php?source_dir=wala-mirror-master/com.ibm.wala.cast.js.rhino/source/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java

2. A BOCK_EXPR in this case first represents iterating (using the above variable) then the result which is the base.

I am not 100% on this but it appears to work!

2018-07-17 12:22 UTC, taufique71 commented
Thanks for the clarification. I understood your first point but still the second one is not clear to me. I don't know if this type of conversation(due to my lack of understanding) is appropriate here or not. May be real-time communication can help better. Would set up a meeting with you after communicating over Slack. Would update the PR after being clear about what I am doing.

2018-07-17 20:55 UTC, mmroz approved these changes
Looks good!

2018-07-18 16:44 UTC, karimhamdanali commented
Have you guys already discussed the final status of this PR? Is it now ready to go?

2018-07-19 06:01 UTC, taufique71 commented
@karimhamdanali I guess it's ready to go. Marked has also approved the changes after our discussion with you and Julian.

2018-07-19 10:13 UTC, karimhamdanali approved these changes

2018-07-19 10:13 UTC, merged