Support for init_existential_addr
uasys/swift pull request #97
Opened 2018-07-17 02:15 UTC by bryantam

Issue #90

2018-07-18 16:45 UTC, karimhamdanali requested changes
Please update the return value to not use `nullptr`.

2018-07-20 12:54 UTC, karimhamdanali commented
@bryantam, could you please resolve the conflicts now after merging Mark's PR?

2018-07-24 18:20 UTC, bryantam commented
It's ready now

2018-07-24 18:22 UTC, karimhamdanali approved these changes

2018-07-24 18:22 UTC, merged