Support deinit_existential_addr
uasys/swift pull request #99
Opened 2018-07-17 05:23 UTC by bryantam

Issue #98

2018-07-18 16:45 UTC, karimhamdanali commented on lib/WALASupport/SILWalaInstructionVisitor.cpp
> +  return nullptr;
Please update the return value to not use `nullptr`.

2018-07-18 16:46 UTC, karimhamdanali requested changes
Please update the return value to not use `nullptr`.

2018-07-20 03:13 UTC, bryantam commented
Empty node is now returned. But I think we should wait until #106 merged, as the new organization might be messed up

2018-07-20 12:54 UTC, karimhamdanali commented
@bryantam, could you please resolve the conflicts now after merging Mark's PR?

2018-07-24 18:20 UTC, bryantam commented
It's ready now

2018-07-24 18:23 UTC, karimhamdanali commented
Hmm, it still shows some conflicts :S That’s a bit weird, given that the other PR didn’t have any merge conflict issues when I just approved it moments ago. Could you please resolve this one as well?

Thanks!

2018-07-24 18:27 UTC, bryantam commented
oops... It's actually conflicting with my own PR. Fixed.

2018-07-24 18:30 UTC, karimhamdanali approved these changes

2018-07-24 18:30 UTC, merged